# Generated by Django 4.2.11 on 2024-05-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_appnew', '0003_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='prdct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_appnew.sub_category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_appnew.categories')),
            ],
        ),
    ]
