# Generated by Django 4.2.11 on 2024-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_appnew', '0004_prdct'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_organic_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
