# Generated by Django 4.2.11 on 2024-05-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_appnew', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=1000),
        ),
    ]
