# Generated by Django 4.2.11 on 2024-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_appnew', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
